// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKqAStEVuWx3zgtn_7lEA6oL8adrKgN5w',
    appId: '1:258618184347:web:5f260deb2542be628b2c3e',
    messagingSenderId: '258618184347',
    projectId: 'atoz-shop-a8586',
    authDomain: 'atoz-shop-a8586.firebaseapp.com',
    storageBucket: 'atoz-shop-a8586.firebasestorage.app',
    measurementId: 'G-KH10NQFJTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5cNaTF-AYmkyPo20lAATqrSQxwlk73E4',
    appId: '1:258618184347:android:33ca5880e513011c8b2c3e',
    messagingSenderId: '258618184347',
    projectId: 'atoz-shop-a8586',
    storageBucket: 'atoz-shop-a8586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJnS7IQ0OvQCBV09c60ZRKuFP8eUtyxk',
    appId: '1:258618184347:ios:877fc05c7ca359db8b2c3e',
    messagingSenderId: '258618184347',
    projectId: 'atoz-shop-a8586',
    storageBucket: 'atoz-shop-a8586.firebasestorage.app',
    iosBundleId: 'com.example.aToz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJnS7IQ0OvQCBV09c60ZRKuFP8eUtyxk',
    appId: '1:258618184347:ios:877fc05c7ca359db8b2c3e',
    messagingSenderId: '258618184347',
    projectId: 'atoz-shop-a8586',
    storageBucket: 'atoz-shop-a8586.firebasestorage.app',
    iosBundleId: 'com.example.aToz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKqAStEVuWx3zgtn_7lEA6oL8adrKgN5w',
    appId: '1:258618184347:web:755784ccd61f3c368b2c3e',
    messagingSenderId: '258618184347',
    projectId: 'atoz-shop-a8586',
    authDomain: 'atoz-shop-a8586.firebaseapp.com',
    storageBucket: 'atoz-shop-a8586.firebasestorage.app',
    measurementId: 'G-ZT5Q8PCSDQ',
  );
}
