// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KEYAZUTvUXUaEzLNb_VOru9KVE2CXg0',
    appId: '1:638564581387:web:49044aa2f169a7a493470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    authDomain: 'emailauthentication-78e0b.firebaseapp.com',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    measurementId: 'G-R7EKDNE9W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbitWuCiBY9fLP03GfUreNMThxAV1e94',
    appId: '1:638564581387:android:eb912b0de9ae46c093470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7KY13NhOlf0KSKg1CMksCV-khoYDfWd0',
    appId: '1:638564581387:ios:22c3458ff3499d1293470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    androidClientId: '638564581387-mqhmf01p1s1s2j4kjjd8uo59hcsmp7u0.apps.googleusercontent.com',
    iosClientId: '638564581387-u6gtmordoj41uk4ef4skfu1tu3pvh95u.apps.googleusercontent.com',
    iosBundleId: 'com.example.aToZUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7KY13NhOlf0KSKg1CMksCV-khoYDfWd0',
    appId: '1:638564581387:ios:22c3458ff3499d1293470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    androidClientId: '638564581387-mqhmf01p1s1s2j4kjjd8uo59hcsmp7u0.apps.googleusercontent.com',
    iosClientId: '638564581387-u6gtmordoj41uk4ef4skfu1tu3pvh95u.apps.googleusercontent.com',
    iosBundleId: 'com.example.aToZUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9KEYAZUTvUXUaEzLNb_VOru9KVE2CXg0',
    appId: '1:638564581387:web:91193f0eaa16c39793470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    authDomain: 'emailauthentication-78e0b.firebaseapp.com',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    measurementId: 'G-QMD9E35E4E',
  );
}
